version: '3'

tasks:
  setup:
    desc: "Set up virtual environment and install dependencies"
    cmds:
      - chmod +x setup_env.sh
      - ./setup_env.sh

  pipenv-setup:
    desc: "Set up using pipenv specifically"
    cmds:
      - pipenv install -r requirements.txt
      - echo "Environment ready! Run 'task pipenv-shell' to activate"

  pipenv-shell:
    desc: "Activate pipenv shell"
    cmds:
      - pipenv shell

  venv-setup:
    desc: "Set up using standard venv"
    cmds:
      - python3 -m venv venv
      - source venv/bin/activate && pip install -r requirements.txt
      - echo "Environment ready! Run 'source venv/bin/activate' to activate"

  install:
    desc: "Install dependencies in current environment"
    cmds:
      - pip install -r requirements.txt

  webapp:
    desc: "Launch Streamlit web application"
    cmds:
      - streamlit run webapp.py

  run:
    desc: "Run CLI analysis with example config"
    cmds:
      - python run_analysis.py example_config.json

  run-config:
    desc: "Run CLI analysis with custom config (usage: task run-config -- config.json)"
    cmds:
      - python run_analysis.py {{.CLI_ARGS}}

  test:
    desc: "Run core test suite"
    cmds:
      - python test_zscore_calculations.py

  test-webapp:
    desc: "Run Streamlit webapp integration tests"
    cmds:
      - python -m pytest test_webapp_integration.py -v --tb=short

  test-all:
    desc: "Run all tests in the project"
    cmds:
      - echo "Running core test suite..."
      - python test_zscore_calculations.py -q
      - echo "Running pytest-based integration tests..."
      - python -m pytest test_webapp_integration.py test_url_state_loading_integration.py test_20_scans.py test_auto_update.py test_data_editor.py test_url_loading_bug_reproduction.py -v --tb=short
      - echo "Running simple integration tests..."
      - python test_integration_simple.py
      - python test_url_sharing.py

  help-config:
    desc: "Show configuration help"
    cmds:
      - python run_analysis.py --help-config

  clean:
    desc: "Clean up generated files"
    cmds:
      - rm -f *.png *.csv

  clean-env:
    desc: "Remove virtual environments"
    cmds:
      - rm -rf venv
      - pipenv --rm || true